### ISSUE TITLE
cuda error?

### ISSUE THREAD

**Issue by rlczddl** [superxjm/GlobalNonrigidRegistration#2]
Hi,I encountered this error when compiling: 
FilterPointCould_cuda.o:-1: error: LNK2019: 无法解析的外部符号__cudaRegisterLinkedBinary_52_tmpxft_00004ca8_00000000_10_FilterPointCould_cpp1_ii_902c4f14，该符号在函数 "void __cdecl __nv_cudaEntityRegisterCallback(void * *)" (?__nv_cudaEntityRegisterCallback@@YAXPEAPEAX@Z) 中被引用".
This is my environment: win10,cuda10,qt5.13.0.The libraries are all using your provided.
Any suggestion？
![image](https://user-images.githubusercontent.com/21055131/68356536-84c78800-014d-11ea-8f7d-7124280fdf61.png)

**Comment by superxjm** [comment]
Hi, I use cuda 9.1 in my project and all the related libraries, can you change to cuda 9.1 and check if it is ok?

**Comment by rlczddl** [comment]
HI,I tried but it still doesn't work, and the same error occurs.
